Repository pfnet/pytorch-pfn-extras, pull requests merged in 2021-11, with the labels that each got.

#400 New comparer interface
  pytorch_pfn_extras/training/manager.py
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:feature

#405 Fix comparer to support also for tuple/namedtuple outputs
  pytorch_pfn_extras/handler/_logic.py
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:enhancement

#421 Allow to return dict of `DeferredResult`
  pytorch_pfn_extras/handler/_handler.py
  tests/pytorch_pfn_extras_tests/test_handler.py
Labels: cat:enhancement, prio:high

#423 Make comparer error message comfortable
  pytorch_pfn_extras/utils/comparer.py
Labels: cat:enhancement

#425 Fix comparer for trainer with evaluator
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:bug

#424 Raise UserWarning if `val_loader` is given whereas evaluator is missing in Comparer
  pytorch_pfn_extras/training/_trainer.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_comparer.py
Labels: cat:enhancement

#428 Enforce use of `ppe.to`
  example/mnist_trainer.py
  pytorch_pfn_extras/handler/_handler.py
  tests/pytorch_pfn_extras_tests/training_tests/test_evaluator_metrics.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_comparer.py
Labels: cat:enhancement, no-compat

#406 Add JITRuntime test
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_jit_runtime.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:test

#414 Comparer intermediate value
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_jit_runtime.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:feature

#431 Add function type annotation in extensions
  pytorch_pfn_extras/training/_manager_protocol.py
  pytorch_pfn_extras/training/extensions/_snapshot.py
  pytorch_pfn_extras/training/extensions/fail_on_non_number.py
  pytorch_pfn_extras/training/extensions/log_report.py
  pytorch_pfn_extras/training/extensions/lr_scheduler.py
  pytorch_pfn_extras/training/extensions/micro_average.py
  pytorch_pfn_extras/training/extensions/parameter_statistics.py
  pytorch_pfn_extras/training/extensions/plot_report.py
  pytorch_pfn_extras/training/extensions/print_report.py
  pytorch_pfn_extras/training/extensions/print_report_notebook.py
  pytorch_pfn_extras/training/extensions/profile_report.py
  pytorch_pfn_extras/training/extensions/progress_bar.py
  pytorch_pfn_extras/training/extensions/progress_bar_notebook.py
  pytorch_pfn_extras/training/extensions/value_observation.py
  pytorch_pfn_extras/training/extensions/variable_statistics_plot.py
  pytorch_pfn_extras/training/manager.py
Labels: cat:enhancement

#434 Add missing `eval_setup` in ComparableHandler
  pytorch_pfn_extras/utils/comparer.py
Labels: cat:bug

#426 Add `ppe.handler.CodeBlock` API
  pytorch_pfn_extras/handler/__init__.py
  pytorch_pfn_extras/handler/_code_block.py
  pytorch_pfn_extras/handler/_logic.py
  pytorch_pfn_extras/runtime/_runtime.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:feature

#432 Fix comparer for trainer with evaluator
  pytorch_pfn_extras/utils/comparer.py
Labels: cat:bug

#439 Fix calling finalize operation twice safe
  pytorch_pfn_extras/writing/_tensorboard_writer.py
  pytorch_pfn_extras/writing/_writer_base.py
Labels: cat:bug

#433 Call `writer.finalize()` in extensions that use the writer
  pytorch_pfn_extras/training/extensions/_snapshot.py
  pytorch_pfn_extras/training/extensions/log_report.py
  pytorch_pfn_extras/training/extensions/plot_report.py
  pytorch_pfn_extras/training/extensions/profile_report.py
  pytorch_pfn_extras/training/extensions/variable_statistics_plot.py
  pytorch_pfn_extras/training/manager.py
Labels: cat:bug

#435 Store ppe version in snapshot and check it
  pytorch_pfn_extras/training/manager.py
  tests/pytorch_pfn_extras_tests/training_tests/test_manager.py
Labels: cat:enhancement

#437 Comparer: Support async mode
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_jit_runtime.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:enhancement
