Repository pfnet/pytorch-pfn-extras, pull requests merged in 2021-12, with the labels that each got.

#443 Typing: _tensor.py
  pytorch_pfn_extras/_tensor.py
Labels: cat:enhancement

#436 Show `warning` if specified value to backprop is not in outputs
  pytorch_pfn_extras/handler/_logic.py
  tests/pytorch_pfn_extras_tests/test_handler.py
Labels: cat:enhancement

#419 Comparer: support serialization
  .flexci/config.pbtxt
  pytorch_pfn_extras/training/_evaluator.py
  pytorch_pfn_extras/training/_trainer.py
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:feature

#452 Reduce test_dump time
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:test

#442 Fix `EOFError` on `TimeSummary` cleanup when running in subprocess
  pytorch_pfn_extras/profiler/_time_summary.py
Labels: cat:bug

#456 Fix import error when onnx is not installed
  pytorch_pfn_extras/onnx/__init__.py
  pytorch_pfn_extras/utils/comparer.py
Labels: cat:bug

#457 Bump version to v0.5.4
  pytorch_pfn_extras/_version.py
Labels: cat:other

#458 Reduce duplicated _normalize_outputs
  pytorch_pfn_extras/handler/_logic.py
Labels: cat:enhancement

#459 Add backward_function option in Logic
  pytorch_pfn_extras/handler/_logic.py
  tests/pytorch_pfn_extras_tests/test_logic.py
Labels: cat:enhancement

#461 Typing: ppe.onnx.load
  pytorch_pfn_extras/onnx/load.py
Labels: cat:enhancement

#460 Typing: ppe.onnx.annotate
  pytorch_pfn_extras/onnx/annotate.py
Labels: cat:enhancement

#462 Typing: strip_large_tensor
  pytorch_pfn_extras/onnx/strip_large_tensor.py
Labels: cat:enhancement
