Repository pfnet/pytorch-pfn-extras, pull requests merged in 2021-10, with the labels that each got.

#387 Publicize `Trainer` and `Evaluator`
  pytorch_pfn_extras/engine.py
  pytorch_pfn_extras/handler/_handler.py
  pytorch_pfn_extras/runtime/_runtime.py
  pytorch_pfn_extras/training/__init__.py
  pytorch_pfn_extras/training/_evaluator.py
  pytorch_pfn_extras/training/_trainer.py
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/training_tests/test_engine.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:enhancement

#392 Keep consuming `async` handler option
  pytorch_pfn_extras/handler/_handler.py
Labels: cat:bug

#412 Support namedtuple containing non-Tensor
  pytorch_pfn_extras/handler/_logic.py
  pytorch_pfn_extras/runtime/_runtime.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:bug, prio:high
