Repository pfnet/pytorch-pfn-extras, pull requests merged in 2022-05, with the labels that each got.

#543 Add `update_via_args` to config
  pytorch_pfn_extras/config.py
  tests/pytorch_pfn_extras_tests/test_config.py
Labels: cat:enhancement

#544 pfto: Updates for torch 1.11
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  stubs/torch/_C/__init__.pyi
Labels: cat:enhancement

#547 Fix the type annotation of LogReport.log
  pytorch_pfn_extras/training/extensions/log_report.py
Labels: cat:enhancement

#549 Update GPG repository key
  .flexci/linux/Dockerfile
Labels: cat:test

#548 Correct type annotation of LogReport
  pytorch_pfn_extras/training/extensions/log_report.py
  pytorch_pfn_extras/training/extensions/print_report.py
Labels: cat:enhancement

#545 Add torch 1.11 in CI matrix
  .flexci/config.pbtxt
  .flexci/linux/build_and_push.sh
  .flexci/windows/test.ps1
  .github/workflows/pretest.yml
Labels: cat:test

#551 PoC implementation for distributed evaluators
  pytorch_pfn_extras/distributed/__init__.py
  pytorch_pfn_extras/distributed/_distributed_validation_sampler.py
  pytorch_pfn_extras/reporting.py
  pytorch_pfn_extras/training/__init__.py
  pytorch_pfn_extras/training/_evaluator.py
  pytorch_pfn_extras/training/extensions/__init__.py
  pytorch_pfn_extras/training/extensions/evaluator.py
  tests/pytorch_pfn_extras_tests/distributed_tests/test_distributed_validation_sampler.py
  tests/pytorch_pfn_extras_tests/test_reporter.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_evaluator.py
Labels: cat:feature
