Repository pfnet/pytorch-pfn-extras, pull requests merged in 2022-03, with the labels that each got.

#524 Fix version check for versions with '-' splitter
  pytorch_pfn_extras/_torch_version.py
Labels: cat:other

#522 Test with CPU in GH actions
  .github/workflows/test-cpu.yml
  tests/pytorch_pfn_extras_tests/utils_tests/test_checkpoint.py
Labels: cat:test

#529 Fix flakiness in `test_progress_bar`
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_progress_bar.py
Labels: cat:test

#523 Add documentation for `_RuntimeRegistry` and `CodeBlock`
  docs/source/user_guide/codeblocks.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/logic.rst
  docs/source/user_guide/runtimes.rst
Labels: cat:docs

#533 Enable to use multiple optimizers in CodeBlock
  pytorch_pfn_extras/handler/_code_block.py
  pytorch_pfn_extras/handler/_logic.py
  pytorch_pfn_extras/runtime/_runtime.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:enhancement

#531 pfto: Fix onnx export of torch.cat
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
Labels: cat:bug

#527 Add `profiler` option to `create_trainer`
  example/mnist_trainer.py
  pytorch_pfn_extras/engine.py
  pytorch_pfn_extras/training/_evaluator.py
  pytorch_pfn_extras/training/_trainer.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:feature
