Repository pfnet/pytorch-pfn-extras, pull requests merged in 2022-07, with the labels that each got.

#554 Add kwarg to create_trainer
  pytorch_pfn_extras/engine.py
Labels: cat:enhancement

#561 Add torch 1.12 in CI matrix
  .flexci/config.pbtxt
  .flexci/linux/build_and_push.sh
  .flexci/windows/test.ps1
  .github/workflows/pretest.yml
Labels: cat:test

#563 [PFTO] Show better error when exporting tuple outputs
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
Labels: cat:enhancement

#558 Separate torch onnx constants for version compatibility
  pytorch_pfn_extras/onnx/_constants.py
  pytorch_pfn_extras/onnx/_globals.py
  pytorch_pfn_extras/onnx/export_testcase.py
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export_testcase.py
Labels: cat:enhancement

#564 [PFTO] Complement model opset imports from graph nodes'
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
Labels: cat:enhancement

#568 Fix mypy failures for torch 1.12
  pytorch_pfn_extras/nn/modules/lazy.py
  pytorch_pfn_extras/nn/parallel/distributed.py
  pytorch_pfn_extras/onnx/_constants.py
  pytorch_pfn_extras/onnx/_globals.py
  pytorch_pfn_extras/onnx/export_testcase.py
Labels: cat:code-fix

#569 Use `torch.onnx._CAFFE2_ATEN_FALLBACK`
  pytorch_pfn_extras/onnx/export_testcase.py
Labels: cat:enhancement

#567 Use `torch.testing.assert_close`
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/test_handler.py
Labels: cat:test

#570 Small test fixes for torch 1.12
  tests/pytorch_pfn_extras_tests/onnx_tests/test_annotate.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_torchvision.py
Labels: cat:test

#582 Rename `config` to `options` in `ppe.to`
  pytorch_pfn_extras/runtime/_to.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_to.py
Labels: cat:enhancement, no-compat

#575 Drop torch 1.8 from CI
  .flexci/config.pbtxt
  .flexci/linux/build_and_push.sh
  .flexci/windows/test.ps1
  .github/workflows/pretest.yml
  README.md
Labels: cat:enhancement

#583 Add ppe.map API
  pytorch_pfn_extras/__init__.py
  pytorch_pfn_extras/handler/_code_block.py
  pytorch_pfn_extras/runtime/_map.py
  pytorch_pfn_extras/runtime/_runtime.py
  pytorch_pfn_extras/runtime/_to.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_jit_runtime.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_runtime.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_to.py
  tests/pytorch_pfn_extras_tests/test_handler.py
Labels: cat:feature
