Repository pfnet/pytorch-pfn-extras, pull requests merged in 2022-10, with the labels that each got.

#602 [onnx] Disable logging in non-verbose
  pytorch_pfn_extras/onnx/export_testcase.py
Labels: cat:enhancement

#608 [CI] Use cpu torch package instead
  .github/workflows/pretest.yml
  .github/workflows/test-cpu.yml
Labels: cat:test

#604 Always create expected output for export_testcase
  pytorch_pfn_extras/onnx/_grad.py
  pytorch_pfn_extras/onnx/export_testcase.py
Labels: cat:enhancement

#605 [ONNX] Support custom_opsets in PFTO
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
Labels: cat:enhancement

#607 [PFTO] Flatten nested outputs like torch.onnx
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/utils.py
Labels: cat:enhancement

#603 [torchscript] Add torchscript utility to find inplace op
  pytorch_pfn_extras/torchscript.py
  tests/pytorch_pfn_extras_tests/test_torchscript.py
Labels: cat:feature

#616 Update for pytest 7.2
  tests/pytorch_pfn_extras_tests/dataset_tests/tabular_tests/test_transform.py
Labels: cat:test

#615 [CI] Test with nightly torch daily
  .github/workflows/nightly-test-cpu.yml
Labels: cat:test

#612 [TS] Move post jit pass lint utility to torchscript module
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  pytorch_pfn_extras/torchscript.py
Labels: cat:feature
