Repository pfnet/pytorch-pfn-extras, pull requests merged in 2022-02, with the labels that each got.

#507 Fix type hint
  pytorch_pfn_extras/engine.py
Labels: cat:bug

#484 [ONNX] Add pure python torch.onnx.export implementation
  .github/workflows/pretest.yml
  pytest.ini
  pytorch_pfn_extras/onnx/_as_output.py
  pytorch_pfn_extras/onnx/export_testcase.py
  pytorch_pfn_extras/onnx/pfto_exporter/__init__.py
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  setup.py
  stubs/torch/_C/__init__.pyi
  tests/pytorch_pfn_extras_tests/onnx_tests/test_annotate.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_as_output.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export_testcase.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_grad.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_torchvision.py
  tests/pytorch_pfn_extras_tests/onnx_tests/utils.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_jit_runtime.py
Labels: cat:feature

#509 Mark cuda required tests to run tests in cpu only device
  tests/pytorch_pfn_extras_tests/cuda_tests/test_allocator.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_torchvision.py
  tests/pytorch_pfn_extras_tests/profiler_tests/test_record.py
  tests/pytorch_pfn_extras_tests/test_handler.py
  tests/pytorch_pfn_extras_tests/test_logic.py
  tests/pytorch_pfn_extras_tests/test_reporter.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:test

#514 Fix `trainer.extend` annotation to accept `ExtensionEntry`
  pytorch_pfn_extras/engine.py
  pytorch_pfn_extras/training/_trainer.py
Labels: cat:bug

#516 Fix `UnboundLocalError` in pfto exporter
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
Labels: cat:bug

#486 Change `out_dir` to better reflect the fs needs
  pytorch_pfn_extras/training/manager.py
  pytorch_pfn_extras/writing/_parallel_writer.py
  pytorch_pfn_extras/writing/_queue_writer.py
  pytorch_pfn_extras/writing/_simple_writer.py
  pytorch_pfn_extras/writing/_tensorboard_writer.py
  pytorch_pfn_extras/writing/_writer_base.py
Labels: cat:enhancement, no-compat

#518 Best observation extension
  docs/source/reference/index.rst
  pytorch_pfn_extras/training/extensions/__init__.py
  pytorch_pfn_extras/training/extensions/best_value.py
  pytorch_pfn_extras/training/triggers/minmax_value_trigger.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_best_value.py
Labels: cat:feature
