Repository pfnet/pytorch-pfn-extras, pull requests merged in 2022-11, with the labels that each got.

#622 [onnx] Make tests pass in torch 1.13
  .github/workflows/pretest.yml
  pytest.ini
  pytorch_pfn_extras/nn/parallel/distributed.py
  pytorch_pfn_extras/onnx/_constants.py
  pytorch_pfn_extras/onnx/annotate.py
  pytorch_pfn_extras/onnx/export_testcase.py
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  pytorch_pfn_extras/onnx/symbolic_registry.py
  stubs/torch/_C/__init__.pyi
  tests/pytorch_pfn_extras_tests/onnx_tests/test_annotate.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_as_output.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export_testcase.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_grad.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_torchvision.py
Labels: cat:enhancement

#610 [PFTO] Restore rng_state before running model
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/utils.py
Labels: cat:bug

#623 Bump version to v0.6.2
  pytorch_pfn_extras/_version.py
Labels: cat:other, prio:high

#625 Add @asi1024 @emcastillo @kmaehashi to codeowners
  .github/CODEOWNERS
Labels: cat:other

#628 [onnx] Fix deprecated warning message matching from torch.onnx
  pytest.ini
Labels: cat:test

#630 Suppress jupyter warnings
  .github/workflows/nightly-test-cpu.yml
  .github/workflows/test-cpu.yml
Labels: cat:test

#632 Suppress platform directory warnings in flexci
  .flexci/linux/unittest.sh
  .flexci/windows/test.ps1
Labels: cat:test

#631 [onnx] Avoid circular import by lazy import
  pytorch_pfn_extras/onnx/annotate.py
Labels: cat:bug

#634 [pfto] Lazy evaluate logging
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
Labels: cat:enhancement

#633 [pfto] Lazy import symbolic registry for circular dependency
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
Labels: cat:enhancement

#635 Suppress np.bool8 warnings
  tests/pytorch_pfn_extras_tests/test_writing.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_log_report.py
Labels: cat:test
