Repository pfnet/pytorch-pfn-extras, pull requests merged in 2022-01, with the labels that each got.

#479 Typing: dataloaders.utils
  pytorch_pfn_extras/dataloaders/utils.py
Labels: cat:enhancement

#483 Make sure to open a snapshot file in binary mode
  pytorch_pfn_extras/training/extensions/_snapshot.py
  pytorch_pfn_extras/writing/_writer_base.py
Labels: cat:enhancement

#487 Add `train_epoch_end` to runtime
  pytorch_pfn_extras/handler/_handler.py
  pytorch_pfn_extras/runtime/_runtime.py
  tests/pytorch_pfn_extras_tests/test_handler.py
Labels: cat:feature

#481 Typing: Use Sequence/Mapping instead of List/Dict
  pytorch_pfn_extras/config.py
  pytorch_pfn_extras/engine.py
  pytorch_pfn_extras/reporting.py
  pytorch_pfn_extras/training/_evaluator.py
  pytorch_pfn_extras/training/_manager_protocol.py
  pytorch_pfn_extras/training/extensions/print_report.py
  pytorch_pfn_extras/training/manager.py
  pytorch_pfn_extras/writing/_writer_base.py
Labels: cat:enhancement

#493 Fix IPython display import
  pytorch_pfn_extras/training/extensions/print_report_notebook.py
  pytorch_pfn_extras/training/extensions/progress_bar_notebook.py
Labels: cat:enhancement

#476 [ONNX] Clear old test data in overwriting export
  pytorch_pfn_extras/onnx/export_testcase.py
Labels: cat:enhancement

#469 Comparer: Add baseline option
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:enhancement

#478 [ONNX] Skip metadata export in test if possible
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export_testcase.py
Labels: cat:test

#482 Raise error for nested runtime
  pytorch_pfn_extras/handler/_handler.py
  pytorch_pfn_extras/runtime/_runtime.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_to.py
Labels: cat:enhancement

#477 [onnx] Unstrip script
  docs/source/user_guide/onnx.md
  pytorch_pfn_extras/onnx/unstrip_tensor.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export_testcase.py
Labels: cat:feature

#490 Fix ExtensionsManager to call Extension.on_error
  pytorch_pfn_extras/training/manager.py
  tests/pytorch_pfn_extras_tests/training_tests/test_extension.py
Labels: cat:bug, prio:high

#485 [ONNX] Add warning to enable metadata in strip mode
  pytorch_pfn_extras/onnx/export_testcase.py
Labels: cat:enhancement

#489 Add an example for comparer
  .flexci/linux/unittest.sh
  example/mnist_trainer.py
Labels: cat:other

#480 Typing: comparer
  pytorch_pfn_extras/utils/comparer.py
Labels: cat:enhancement

#472 Support multiple evaluators
  pytorch_pfn_extras/engine.py
  pytorch_pfn_extras/training/_trainer.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:enhancement

#491 Add helper function to initialize OpenMPI environments
  docs/source/reference/index.rst
  example/mnist_ddp.py
  pytorch_pfn_extras/distributed/__init__.py
  pytorch_pfn_extras/distributed/_initialize.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_distributed_snapshot.py
Labels: cat:feature, prio:high

#498 Disable profiler by default in trainer/manager (no-compat)
  pytorch_pfn_extras/profiler/_record.py
  pytorch_pfn_extras/training/_trainer.py
  pytorch_pfn_extras/training/manager.py
Labels: cat:enhancement, no-compat

#413 Add CI for PyTorch 1.10
  .flexci/config.pbtxt
  .flexci/linux/build_and_push.sh
  .flexci/windows/_flexci.ps1
  .flexci/windows/test.ps1
  .github/workflows/pretest.yml
  pytorch_pfn_extras/onnx/export_testcase.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_grad.py
Labels: cat:test

#500 Bump version to v0.5.6
  pytorch_pfn_extras/_version.py
Labels: cat:other

#501 Add version check function for special torch package version names
  .github/workflows/pretest.yml
  pytorch_pfn_extras/__init__.py
  pytorch_pfn_extras/_torch_version.py
  pytorch_pfn_extras/onnx/export_testcase.py
  setup.py
  tests/pytorch_pfn_extras_tests/nn_tests/parallel_tests/test_distributed.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_annotate.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_as_output.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export_testcase.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_grad.py
  tests/pytorch_pfn_extras_tests/profiler_tests/test_record.py
Labels: cat:feature

#502 Add `check_grad` option to `FailOnNonNumber` extension
  pytorch_pfn_extras/training/extensions/fail_on_non_number.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_fail_on_non_number.py
Labels: cat:enhancement

#499 Fix filename format of `comparer.dump(evaluator)`
  .flexci/linux/unittest.sh
  pytorch_pfn_extras/utils/comparer.py
Labels: cat:bug

#504 Remove unused summary file in comparer
  pytorch_pfn_extras/utils/comparer.py
Labels: cat:enhancement

#503 Fix comparer to create dump directory if not exists
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/utils_tests/test_new_comparer.py
Labels: cat:enhancement

#506 Add `train_cleanup` runtime & handler hook
  pytorch_pfn_extras/handler/_handler.py
  pytorch_pfn_extras/runtime/_runtime.py
  pytorch_pfn_extras/training/_trainer.py
  tests/pytorch_pfn_extras_tests/test_handler.py
Labels: cat:enhancement
