Repository pfnet/pytorch-pfn-extras, pull requests merged in 2022-08, with the labels that each got.

#580 Fix torch mypy stub checking
  .github/workflows/pretest.yml
  pytorch_pfn_extras/onnx/__init__.py
  pytorch_pfn_extras/onnx/__init__.pyi
Labels: cat:enhancement

#581 Add a `finalize` method to `Trainer` and `ExtensionsManager` and finalize extensions when error is raised during iteration
  pytorch_pfn_extras/training/_trainer.py
  pytorch_pfn_extras/training/manager.py
  tests/pytorch_pfn_extras_tests/training_tests/test_extension.py
  tests/pytorch_pfn_extras_tests/training_tests/test_manager.py
Labels: cat:enhancement, no-compat

#526 Add a extension to post to Slack
  .flexci/linux/build_and_push.sh
  .flexci/windows/test.ps1
  docs/source/reference/index.rst
  example/mnist.py
  pytorch_pfn_extras/training/extensions/__init__.py
  pytorch_pfn_extras/training/extensions/slack.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_slack.py
Labels: cat:feature

#589 Use ubuntu-22.04 as GitHub Actions runner image
  .github/workflows/pretest.yml
  .github/workflows/test-cpu.yml
Labels: cat:test

#588 Ignore runtime class for torch.save/load
  pytorch_pfn_extras/runtime/_runtime.py
  tests/pytorch_pfn_extras_tests/runtime_tests/test_to.py
Labels: cat:enhancement

#576 Support Python 3.10
  .flexci/linux/build_and_push.sh
  .flexci/windows/test.ps1
  pytest.ini
Labels: cat:enhancement

#593 CI: build docker images in each executions and reuse images cached in registry
  .flexci/config.pbtxt
  .flexci/linux/build_and_push.sh
  .flexci/linux/main-flexci.sh
  .flexci/linux/script.sh
Labels: cat:test

#597 Fix import failure when user account does not exist
  pytorch_pfn_extras/training/extensions/slack.py
Labels: cat:bug

#598 Bump version to v0.6.1
  pytorch_pfn_extras/_version.py
Labels: cat:other
