Repository pfnet/pytorch-pfn-extras, pull requests merged in 2023-06, with the labels that each got.

#684 [pfto] Fix empty list handling in make_attribute
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_grad.py
Labels: cat:bug

#669 [pfto] Support alias parameter
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
Labels: cat:enhancement

#694 add pysen config for example linter
  .github/workflows/pretest-and-test.yml
  example/pysen.toml
Labels: cat:other

#706 Drop torch 1.9 from CIs and add Python 3.8
  .flexci/config.pbtxt
  .flexci/linux/build_and_push.sh
  .flexci/windows/test.ps1
  .github/workflows/pretest-and-test.yml
  README.md
  pytorch_pfn_extras/handler/_logic.py
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  pytorch_pfn_extras/runtime/_autocast.py
  pytorch_pfn_extras/utils/comparer.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_as_output.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export_testcase.py
  tests/pytorch_pfn_extras_tests/profiler_tests/test_record.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:other

#708 Fix key error in non persistent parameter
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
Labels: cat:bug

#709 Use onnxruntime 1.15.1 in windows CI
  .flexci/windows/test.ps1
Labels: cat:test

#710 Ignore scalar deprecation warning in NumPy 1.25
  pytest.ini
Labels: cat:enhancement

#702 Snapshot function of state object in options
  pytorch_pfn_extras/engine.py
  pytorch_pfn_extras/training/__init__.py
  pytorch_pfn_extras/training/_manager_protocol.py
  pytorch_pfn_extras/training/manager.py
  tests/pytorch_pfn_extras_tests/training_tests/test_manager.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:enhancement

#716 Enable state_dict management for options in the tree structure
  pytorch_pfn_extras/engine.py
  tests/pytorch_pfn_extras_tests/training_tests/test_engine.py
Labels: cat:enhancement

#696 change pysen python_version to python3.8
  pyproject.toml
  setup.cfg
Labels: cat:code-fix
