Repository pfnet/pytorch-pfn-extras, pull requests merged in 2023-05, with the labels that each got.

#668 Fix autocast option consumption
  pytorch_pfn_extras/handler/_logic.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:bug

#686 Bump version to v0.6.7
  pytorch_pfn_extras/_version.py
Labels: cat:other

#692 Also look for snapshot in ``writer.out_dir``
  pytorch_pfn_extras/training/extensions/_snapshot.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_snapshot.py
Labels: cat:enhancement

#695 [onnx] Inherit training status in as output module
  pytorch_pfn_extras/onnx/_as_output.py
Labels: cat:test

#697 Fix evaluator recover mode
  pytorch_pfn_extras/handler/_logic.py
  tests/pytorch_pfn_extras_tests/test_logic.py
Labels: cat:bug

#691 refactor gradscaler assertion
  pytorch_pfn_extras/handler/_logic.py
  pytorch_pfn_extras/runtime/_runtime.py
  tests/pytorch_pfn_extras_tests/test_handler.py
Labels: cat:enhancement
