Repository pfnet/pytorch-pfn-extras, pull requests merged in 2023-07, with the labels that each got.

#715 [pfto] Fix some script export errors
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
Labels: cat:bug

#720 Warn to set training when exporting with output_grad
  pytorch_pfn_extras/onnx/export_testcase.py
Labels: cat:enhancement

#725 remove technical preview comments
  docs/source/reference/index.rst
  docs/source/user_guide/trainer.rst
Labels: cat:docs

#726 Set current_device of CUDAWorker thread
  pytorch_pfn_extras/profiler/_time_summary.py
Labels: cat:bug

#727 add release automation workflow
  .github/workflows/publish.yml
Labels: cat:other
