Repository pfnet/pytorch-pfn-extras, pull requests merged in 2023-04, with the labels that each got.

#653 Support pytorch 2.0
  .flexci/linux/build_and_push.sh
  .flexci/windows/test.ps1
  .github/workflows/pretest.yml
  pytorch_pfn_extras/logging.py
  pytorch_pfn_extras/onnx/_as_output.py
  pytorch_pfn_extras/onnx/_lax.py
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  pytorch_pfn_extras/onnx/unstrip_tensor.py
  pytorch_pfn_extras/training/extension.py
  pytorch_pfn_extras/training/manager.py
  pytorch_pfn_extras/utils/checkpoint.py
  pytorch_pfn_extras/utils/comparer.py
  pytorch_pfn_extras/writing/_tensorboard_writer.py
  stubs/torch/_C/__init__.pyi
Labels: cat:enhancement

#657 Add a Logic class for clousure mode optimization.
  pytorch_pfn_extras/handler/__init__.py
  pytorch_pfn_extras/handler/_logic.py
  tests/pytorch_pfn_extras_tests/test_handler.py
  tests/pytorch_pfn_extras_tests/training_tests/test_trainer.py
Labels: cat:enhancement

#649 Enable new PyTorch autocast
  pytorch_pfn_extras/handler/_logic.py
  pytorch_pfn_extras/runtime/_autocast.py
  pytorch_pfn_extras/runtime/_runtime.py
  tests/pytorch_pfn_extras_tests/test_handler.py
Labels: cat:enhancement

#624 [CI] Merge pretest and cpu test
  .github/workflows/pretest-and-test.yml
  .github/workflows/test-cpu.yml
Labels: cat:test

#660 Fix Autocast call in closure logic
  pytorch_pfn_extras/handler/_logic.py
Labels: cat:bug

#659 Bump version to v0.6.6
  pytorch_pfn_extras/_version.py
Labels: cat:other

#665 Use correct torch version in cpu tests
  .github/workflows/pretest-and-test.yml
  pytest.ini
Labels: cat:test

#670 Use state_dict to decide name of initializers
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
Labels: cat:enhancement
