Repository pfnet/pytorch-pfn-extras, pull requests merged in 2023-03, with the labels that each got.

#644 Add no_grad helper
  pytorch_pfn_extras/onnx/__init__.py
  pytorch_pfn_extras/onnx/_helper.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_helper.py
Labels: cat:feature

#650 Fix onnx test directory owner
  .github/CODEOWNERS
Labels: cat:bug

#648 Export control-flow Ops in ppe.onnx.export
  pytorch_pfn_extras/onnx/__init__.py
  pytorch_pfn_extras/onnx/_as_output.py
  pytorch_pfn_extras/onnx/_grad.py
  pytorch_pfn_extras/onnx/_lax.py
  pytorch_pfn_extras/onnx/export_testcase.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_as_output.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_grad.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_lax.py
Labels: cat:feature

#647 Add complex export test in pfto
  pytorch_pfn_extras/onnx/pfto_exporter/export.py
  tests/pytorch_pfn_extras_tests/onnx_tests/test_export.py
Labels: cat:test
