Repository pfnet/pytorch-pfn-extras, pull requests merged in 2023-11, with the labels that each got.

#780 Fix on_error method in DistributedSnapshot
  pytorch_pfn_extras/training/extensions/_snapshot.py
Labels: cat:bug

#742 Support chrome tracing in ppe.profiler
  docs/source/reference/index.rst
  example/mnist_trainer.py
  pytorch_pfn_extras/nn/parallel/distributed.py
  pytorch_pfn_extras/profiler/__init__.py
  pytorch_pfn_extras/profiler/_record.py
  pytorch_pfn_extras/profiler/_time_summary.py
  pytorch_pfn_extras/profiler/_tracing.py
  pytorch_pfn_extras/profiler/_util.py
  pytorch_pfn_extras/training/_trainer.py
  pytorch_pfn_extras/training/extensions/__init__.py
  pytorch_pfn_extras/training/extensions/timeline_trace.py
  pytorch_pfn_extras/training/manager.py
  tests/pytorch_pfn_extras_tests/dataloader_test/test_dataloader.py
  tests/pytorch_pfn_extras_tests/profiler_tests/test_record.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_timeline_trace.py
Labels: cat:feature

#788 Fix nightly test
  pytorch_pfn_extras/distributed/_distributed_validation_sampler.py
  tests/pytorch_pfn_extras_tests/distributed_tests/test_distributed_validation_sampler.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_evaluator.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_progress_bar_notebook.py
  tests/pytorch_pfn_extras_tests/training_tests/test_manager.py
Labels: cat:test

#793 Ignore BrokenBarrierError in comparer test
  pytorch_pfn_extras/utils/comparer.py
Labels: cat:bug

#786 Add more type annotation of np.zeros
  pytorch_pfn_extras/training/extensions/variable_statistics_plot.py
Labels: cat:code-fix

#789 Trigger for using user custom functions
  pytorch_pfn_extras/training/triggers/__init__.py
  pytorch_pfn_extras/training/triggers/function_trigger.py
  tests/pytorch_pfn_extras_tests/training_tests/triggers_tests/test_function_trigger.py
Labels: cat:feature
