Repository pfnet/pytorch-pfn-extras, pull requests merged in 2023-08, with the labels that each got.

#732 Add _cleanup hook only for saver_rank
  pytorch_pfn_extras/training/extensions/_snapshot.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_distributed_snapshot.py
Labels: cat:bug

#738 Fix float epoch trigger
  pytorch_pfn_extras/training/triggers/interval_trigger.py
  tests/pytorch_pfn_extras_tests/training_tests/triggers_tests/test_interval_trigger.py
Labels: cat:bug

#739 Change to the test code directory of the handler/logic module.
  tests/pytorch_pfn_extras_tests/handler_tests/__init__.py
  tests/pytorch_pfn_extras_tests/handler_tests/test_handler.py
  tests/pytorch_pfn_extras_tests/handler_tests/test_logic.py
Labels: cat:code-fix

#731 Automatically generate API References
  docs/requirements.txt
  docs/source/_templates/autosummary/class.rst
  docs/source/_templates/autosummary/module.rst
  docs/source/conf.py
  docs/source/reference/index.rst
Labels: cat:docs

#737 Add wait_for_first_optimizer_step mode
  pytorch_pfn_extras/training/extensions/lr_scheduler.py
  tests/pytorch_pfn_extras_tests/training_tests/extensions_tests/test_lr_scheduler.py
Labels: cat:enhancement

#745 Propagate device index of torch.cuda.Stream in stream context
  pytorch_pfn_extras/cuda/_allocator.py
Labels: cat:enhancement

#743 Add quick start docs
  .flexci/linux/unittest.sh
  docs/source/_example/quick_start_log.py
  docs/source/_example/quick_start_progress.py
  docs/source/_example/quick_start_save.py
  docs/source/_example/quick_start_trainer.py
  docs/source/user_guide/index.rst
  docs/source/user_guide/quick_start.rst
Labels: cat:docs

#747 bump version to v0.7.2
  pytorch_pfn_extras/_version.py
Labels: cat:other
